/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.curriculo;

import javax.swing.JOptionPane;

/**
 *
 * @author 182310002
 */
public class Painel extends javax.swing.JFrame {
     boolean proximo=false;
     boolean mesSelecionado = false;
     boolean diaSelecionado = false;
     boolean anoSelecionado = false;
     boolean estadocivilSelecionado=false;
     boolean cnhSelecionado=false;
     boolean nomeSelecionado=false;
     boolean enderSelecionado=false;
     boolean sobrenomeSelecionado=false;
     boolean cidadeSelecionado=false;
     boolean estadoSelecionado=false;
     boolean cepSelecionado=false;
     boolean telefoneSelecionado=false;
     boolean emailSelecionado=false;
     boolean nacioSelecionado=false;
     boolean instituicaiSelecionado=false;
     boolean localensinoSelecionado=false;
     boolean diplomaSelecionado=false;
     boolean campoSelecionado=false;
     boolean situacaoSelecionado=false;
     boolean mesinicioSelecionado=false;
     boolean mesterminoSelecionado=false;
     boolean anoinicioSelecionado=false;
     boolean anoterminoSelecionado=false;
     boolean semdataSelecionado=false;
     boolean titulocargoSelecionado=false;
     boolean cidadeProSelecionado=false;
     boolean empregadorSelecionado=false;
     boolean estadoProSelecionado=false;
     boolean anoInicioProSelecionado=false;
     boolean anoTerminoProSelecionado=false;
     boolean trabalhajaSelecionado=false;
     boolean semExpSelecionado=false;
     
     
    /**
     * Creates new form Painel
     */
    public Painel() {
       
        initComponents();
        JBproximo.setEnabled(false);
        JBproximoFormacao.setEnabled(false);
        JBProximoProfi.setEnabled(false);
        abas.setEnabledAt(1, false);
        abas.setEnabledAt(2, false);
         
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        abas = new javax.swing.JTabbedPane();
        Abas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTnome = new javax.swing.JTextField();
        JBproximo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTFsobrenome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFendereço = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFcidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFestado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFcep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTFtelefone = new javax.swing.JTextField();
        JTFemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTFnacionalidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JCBmes = new javax.swing.JComboBox<>();
        JCBdia = new javax.swing.JComboBox<>();
        JCBano = new javax.swing.JComboBox<>();
        JCBestadocivil = new javax.swing.JComboBox<>();
        JCBcnh = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JTFinstituicao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JTFlocalInst = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JTFcampoDeEstdo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JTFdiploma = new javax.swing.JTextField();
        JCBmesInicio = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        JCBanoInicio = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JBproximoFormacao = new javax.swing.JButton();
        JCBanotermino = new javax.swing.JComboBox<>();
        JCBmesTermino = new javax.swing.JComboBox<>();
        JCBsituacao = new javax.swing.JComboBox<>();
        JRBsemData = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        JTFempregador = new javax.swing.JTextField();
        JBProximoProfi = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        JTFestadoPro = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        JTFcidadePro = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        JTFtitulocargo = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        JRBtrabalhaja = new javax.swing.JRadioButton();
        JCBanoinicioPro = new javax.swing.JComboBox<>();
        JCBanoterminoPRO = new javax.swing.JComboBox<>();
        JRBsemExp = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAresumo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome ");

        JTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnomeActionPerformed(evt);
            }
        });

        JBproximo.setText("Proximo");
        JBproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBproximoActionPerformed(evt);
            }
        });

        jLabel2.setText("Sobrenome");

        JTFsobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFsobrenomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Endereço: ");

        JTFendereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFendereçoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cidade");

        JTFcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcidadeActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado");

        JTFestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFestadoActionPerformed(evt);
            }
        });

        jLabel6.setText("CEP");

        JTFcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcepActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone");

        JTFtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtelefoneActionPerformed(evt);
            }
        });

        JTFemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFemailActionPerformed(evt);
            }
        });

        jLabel8.setText("E-mail");

        JTFnacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFnacionalidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Nacionalidade");

        jLabel10.setText("Data de Nascimento ");

        jLabel11.setText("Estado Civil ");

        jLabel12.setText("Carteira Nacional de Habilitação");

        JCBmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês()", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        JCBmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBmesActionPerformed(evt);
            }
        });

        JCBdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia()", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        JCBdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBdiaActionPerformed(evt);
            }
        });

        JCBano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano()", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        JCBano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBanoActionPerformed(evt);
            }
        });

        JCBestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione()", "Solteiro", "Casado", "Viúvo", "Divorciado", "União Estavel" }));
        JCBestadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBestadocivilActionPerformed(evt);
            }
        });

        JCBcnh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione()", "A", "B", "C", "D", "E", "Não Habilitado" }));
        JCBcnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBcnhActionPerformed(evt);
            }
        });

        jButton2.setText("Foto");

        javax.swing.GroupLayout AbasLayout = new javax.swing.GroupLayout(Abas);
        Abas.setLayout(AbasLayout);
        AbasLayout.setHorizontalGroup(
            AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbasLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbasLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(167, 167, 167))
                            .addComponent(JTFsobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JTFendereço, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(AbasLayout.createSequentialGroup()
                                            .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(JTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(JTFestado, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(JTFcep, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(AbasLayout.createSequentialGroup()
                                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(JTFtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(JCBestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(AbasLayout.createSequentialGroup()
                                                .addComponent(JCBdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JCBano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11))
                                        .addGap(13, 13, 13)
                                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTFemail)
                                            .addComponent(JTFnacionalidade)
                                            .addGroup(AbasLayout.createSequentialGroup()
                                                .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel12))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(JCBcnh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(JBproximo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        AbasLayout.setVerticalGroup(
            AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbasLayout.createSequentialGroup()
                .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbasLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE))
                    .addGroup(AbasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFendereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbasLayout.createSequentialGroup()
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AbasLayout.createSequentialGroup()
                                .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AbasLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(JTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbasLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(JTFcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(AbasLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbasLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbasLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTFnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCBano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCBdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBcnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(JBproximo)
                .addGap(16, 16, 16))
        );

        abas.addTab("Dados Pessoais", Abas);

        jLabel13.setText("Instituição de Ensino");

        JTFinstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFinstituicaoActionPerformed(evt);
            }
        });

        jLabel14.setText("Local da Instituição de ensino ");

        JTFlocalInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFlocalInstActionPerformed(evt);
            }
        });

        jLabel15.setText("Campo de estudo");

        JTFcampoDeEstdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcampoDeEstdoActionPerformed(evt);
            }
        });

        jLabel16.setText("Diploma");

        JTFdiploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdiplomaActionPerformed(evt);
            }
        });

        JCBmesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês()", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        JCBmesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBmesInicioActionPerformed(evt);
            }
        });

        jLabel17.setText("Data de inicio");

        JCBanoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano()", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        JCBanoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBanoInicioActionPerformed(evt);
            }
        });

        jLabel19.setText("Data de término");

        jLabel23.setText("Situação");

        JBproximoFormacao.setText("Proximo");
        JBproximoFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBproximoFormacaoActionPerformed(evt);
            }
        });

        JCBanotermino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano()", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        JCBanotermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBanoterminoActionPerformed(evt);
            }
        });

        JCBmesTermino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês()", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        JCBmesTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBmesTerminoActionPerformed(evt);
            }
        });

        JCBsituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione()", "Estudando", "Formado" }));
        JCBsituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBsituacaoActionPerformed(evt);
            }
        });

        JRBsemData.setText("Sem data de término");
        JRBsemData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBsemDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(JTFinstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(JTFlocalInst, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(JTFdiploma, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jLabel23)
                            .addComponent(JCBsituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(JTFcampoDeEstdo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(JCBmesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCBanoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(JBproximoFormacao)
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(JCBmesTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JCBanotermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(JRBsemData))
                                        .addGap(32, 32, 32)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFlocalInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFinstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFcampoDeEstdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFdiploma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCBmesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBanoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCBmesTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBanotermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRBsemData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(JBproximoFormacao)
                .addContainerGap())
        );

        abas.addTab("Formação", jPanel2);

        jLabel24.setText("Empregador");

        JTFempregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFempregadorActionPerformed(evt);
            }
        });

        JBProximoProfi.setText("Proximo");
        JBProximoProfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProximoProfiActionPerformed(evt);
            }
        });

        jLabel25.setText("Estado");

        JTFestadoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFestadoProActionPerformed(evt);
            }
        });

        jLabel26.setText("Cidade");

        JTFcidadePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcidadeProActionPerformed(evt);
            }
        });

        jLabel29.setText("Titulo do cargo");

        jLabel30.setText("Data de término");

        JTFtitulocargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtitulocargoActionPerformed(evt);
            }
        });

        jLabel34.setText("Data de inicio");

        JRBtrabalhaja.setText("Eu trabalho aqui no momento");
        JRBtrabalhaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBtrabalhajaActionPerformed(evt);
            }
        });

        JCBanoinicioPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano()", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        JCBanoinicioPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBanoinicioProActionPerformed(evt);
            }
        });

        JCBanoterminoPRO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano()", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        JCBanoterminoPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBanoterminoPROActionPerformed(evt);
            }
        });

        JRBsemExp.setText("Não possuo experiência");
        JRBsemExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBsemExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JCBanoinicioPro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(JTFcidadePro, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel29)
                            .addComponent(JTFtitulocargo, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JRBtrabalhaja)
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel30)
                            .addComponent(JTFestadoPro)
                            .addComponent(JTFempregador)
                            .addComponent(JCBanoterminoPRO, 0, 347, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBProximoProfi)
                .addGap(9, 9, 9))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JRBsemExp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(JRBsemExp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFempregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFtitulocargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFestadoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFcidadePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBanoinicioPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBanoterminoPRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRBtrabalhaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(JBProximoProfi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abas.addTab("Experiencia Profissionais", jPanel3);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JTAresumo.setBackground(new java.awt.Color(255, 255, 255));
        JTAresumo.setColumns(20);
        JTAresumo.setRows(5);
        jScrollPane1.setViewportView(JTAresumo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        abas.addTab("Resumo", jPanel4);

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBproximoActionPerformed
         if (estadocivilSelecionado&&cnhSelecionado&&mesSelecionado && diaSelecionado && anoSelecionado&&nomeSelecionado&&sobrenomeSelecionado&&enderSelecionado&&cidadeSelecionado&&estadoSelecionado&&cepSelecionado&&telefoneSelecionado&&emailSelecionado&&nacioSelecionado) {
        JBproximo.setEnabled(true);
       if(evt.getSource()==JBproximo){
            abas.setEnabledAt(1, true);
            abas.setSelectedIndex(1);
       }
        }
      
    }//GEN-LAST:event_JBproximoActionPerformed

    private void JTFendereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFendereçoActionPerformed
           String texto = JTFendereço.getText();
         proximo = (texto != null && !texto.isEmpty());
           if(proximo){
             enderSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFendereçoActionPerformed

    private void JTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnomeActionPerformed
       String texto = JTnome.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             nomeSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTnomeActionPerformed

    private void JBproximoFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBproximoFormacaoActionPerformed
     if (instituicaiSelecionado && localensinoSelecionado && diplomaSelecionado && campoSelecionado && situacaoSelecionado && mesinicioSelecionado&& anoinicioSelecionado&&mesterminoSelecionado&&anoterminoSelecionado||semdataSelecionado) {
    JBproximoFormacao.setEnabled(true);
    if (evt.getSource() == JBproximoFormacao) {
        abas.setEnabledAt(2, true);
        abas.setSelectedIndex(2);
    }
}
    }//GEN-LAST:event_JBproximoFormacaoActionPerformed

    private void JBProximoProfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProximoProfiActionPerformed
     if (titulocargoSelecionado&&cidadeProSelecionado&&empregadorSelecionado&&estadoProSelecionado&&anoInicioProSelecionado&&anoTerminoProSelecionado||trabalhajaSelecionado||semExpSelecionado) {
    JBProximoProfi.setEnabled(true);
    if (evt.getSource() == JBProximoProfi) {
       
        abas.setEnabledAt(3, true);
        abas.setSelectedIndex(3);
          Arquivo arv = new Arquivo();
       arv.gravar("\n\nDADOS PESSOAIS\n\n");
       arv.gravar("\nNome: "+JTnome.getText());
       arv.gravar("\nSobreNome: "+JTFsobrenome.getText());
       arv.gravar("\nEndereço: "+JTFendereço.getText());
       arv.gravar("\nCidade: "+JTFcidade.getText());
       arv.gravar("\nEstado: "+JTFestado.getText());
       arv.gravar("\nCep: "+JTFcep.getText());
       arv.gravar("\nTelefone: "+JTFtelefone.getText());
       arv.gravar("\nEmail: "+JTFemail.getText());
       arv.gravar("\nNacionalidade: "+JTFnacionalidade.getText());
       arv.gravar("\nData de Nascimento: "+JCBdia.getSelectedItem()+"/"+JCBmes.getSelectedItem()+"/"+JCBano.getSelectedItem());
       arv.gravar("\nEstado Civil: "+JCBestadocivil.getSelectedItem());
       arv.gravar("\nCarteira Nacional de Habilitação: "+JCBcnh.getSelectedItem());
       arv.gravar("\n\n---------------------------------------------------------------\n");
       arv.gravar("FORMAÇÃO\n\n");
       arv.gravar("\nInstituição de ensino: "+JTFinstituicao.getText());
       arv.gravar("\nLocal da Instituição de ensino : "+JTFlocalInst.getText());
       arv.gravar("\nDiploma: "+JTFdiploma.getText());
       arv.gravar("\nCampo de estudo: "+JTFcampoDeEstdo.getText());
       arv.gravar("\nSituação: "+JCBsituacao.getSelectedItem());
       arv.gravar("\nData de Inicio: "+JCBmesInicio.getSelectedItem()+"/"+JCBanoInicio.getSelectedItem());
       if(semdataSelecionado){
            arv.gravar("\nData de Termino: Sem Previsão.");
       }else{
            arv.gravar("\nData de Termino: "+JCBmesTermino.getSelectedItem()+"/"+JCBanotermino.getSelectedItem());
       }
       arv.gravar("\n\n---------------------------------------------------------------\n");
       arv.gravar("EXPERIÊNCIA PROFISSIONAL\n\n");
       if(semExpSelecionado){
           arv.gravar("Sem Experiência.");
       }else{
            arv.gravar("\nTitulo do cargo: "+JTFtitulocargo.getText());
            arv.gravar("\nEmpregador: "+JTFempregador.getText());
            arv.gravar("\nCidade: "+JTFcidadePro.getText());
            arv.gravar("\nEstado: "+JTFestadoPro.getText());
            arv.gravar("\nData de Inicio: "+JCBanoinicioPro.getSelectedItem());
       if(trabalhajaSelecionado){
           arv.gravar("\nData de Termino: Atualmente trabalhando.");
       }else{
            arv.gravar("\nData de Termino: "+JCBanoterminoPRO.getSelectedItem());
       }
       }
       arv.ler();
       JTAresumo.setText(arv.ler());
    }
     }
    }//GEN-LAST:event_JBProximoProfiActionPerformed

    private void JTFsobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFsobrenomeActionPerformed
           String texto = JTFsobrenome.getText();
         proximo =(texto != null && !texto.isEmpty());
           if(proximo){
             sobrenomeSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFsobrenomeActionPerformed

    private void JTFcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcidadeActionPerformed
           String texto = JTFcidade.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             cidadeSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFcidadeActionPerformed

    private void JTFestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFestadoActionPerformed
           String texto = JTFestado.getText();
         proximo = (texto != null && !texto.isEmpty());
          if(proximo){
             estadoSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFestadoActionPerformed

    private void JTFcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcepActionPerformed
           String texto = JTFcep.getText();
         proximo = (texto != null && !texto.isEmpty());
          if(proximo){
             cepSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFcepActionPerformed

    private void JTFtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtelefoneActionPerformed
           String texto = JTFtelefone.getText();
         proximo = (texto != null && !texto.isEmpty());
          if(proximo){
             telefoneSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFtelefoneActionPerformed

    private void JTFemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFemailActionPerformed
           String texto = JTFemail.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             emailSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFemailActionPerformed

    private void JTFnacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnacionalidadeActionPerformed
           String texto = JTFnacionalidade.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             nacioSelecionado=true;
        }
          JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JTFnacionalidadeActionPerformed
    private void JCBmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBmesActionPerformed
        if(JCBmes.getSelectedItem() != null){
        mesSelecionado = true;
        }
        JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JCBmesActionPerformed

    private void JCBdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBdiaActionPerformed
        if(JCBdia.getSelectedItem() != null){
              diaSelecionado = true;
           }
        JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JCBdiaActionPerformed

    private void JCBanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBanoActionPerformed
        if(JCBano.getSelectedItem() != null){
              anoSelecionado = true;
        }
        JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JCBanoActionPerformed

    private void JCBcnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBcnhActionPerformed
          if(JCBcnh.getSelectedItem()!=null){
            cnhSelecionado=true;  
          }
         JBproximoActionPerformed(evt);
    }//GEN-LAST:event_JCBcnhActionPerformed

    private void JCBestadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBestadocivilActionPerformed
       if(JCBestadocivil.getSelectedItem()!=null){
            estadocivilSelecionado=true;  
          }
         JBproximoActionPerformed(evt);

    }//GEN-LAST:event_JCBestadocivilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       JOptionPane.showMessageDialog(null,"Dados Salvos com sucesso!", "",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTFinstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFinstituicaoActionPerformed
         String texto = JTFinstituicao.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             instituicaiSelecionado=true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JTFinstituicaoActionPerformed

    private void JTFlocalInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFlocalInstActionPerformed
       String texto = JTFlocalInst.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             localensinoSelecionado=true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JTFlocalInstActionPerformed

    private void JTFdiplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdiplomaActionPerformed
       String texto = JTFdiploma.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             diplomaSelecionado=true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JTFdiplomaActionPerformed

    private void JTFcampoDeEstdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcampoDeEstdoActionPerformed
        String texto = JTFcampoDeEstdo.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
             campoSelecionado=true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JTFcampoDeEstdoActionPerformed

    private void JCBsituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBsituacaoActionPerformed
          if(JCBsituacao.getSelectedItem()!=null){
            situacaoSelecionado=true;  
          }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JCBsituacaoActionPerformed

    private void JCBmesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBmesInicioActionPerformed
           if(JCBmesInicio.getSelectedItem() != null){
              JCBdia.setEnabled(true);
        mesinicioSelecionado = true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JCBmesInicioActionPerformed

    private void JCBmesTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBmesTerminoActionPerformed
         if(JCBmesTermino.getSelectedItem() != null){
              JCBdia.setEnabled(true);
        mesterminoSelecionado = true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JCBmesTerminoActionPerformed

    private void JCBanoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBanoInicioActionPerformed
       if(JCBanoInicio.getSelectedItem() != null){
        anoinicioSelecionado = true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JCBanoInicioActionPerformed

    private void JCBanoterminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBanoterminoActionPerformed
       if(JCBanotermino.getSelectedItem() != null){
        anoterminoSelecionado = true;
        }
          JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JCBanoterminoActionPerformed

    private void JRBsemDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBsemDataActionPerformed
       if(JRBsemData.isSelected()){
           semdataSelecionado=true;
           JCBmesTermino.setEnabled(false);
           JCBanotermino.setEnabled(false);
       } 
       if(!JRBsemData.isSelected()){
           semdataSelecionado=false;
            mesterminoSelecionado=false;
            anoterminoSelecionado=false;
           JCBanotermino.setEnabled(true);
            JBproximoFormacao.setEnabled(false);
           JCBmesTermino.setEnabled(true);
           JCBanotermino.setEnabled(true);
       }
        JBproximoFormacaoActionPerformed(evt);
    }//GEN-LAST:event_JRBsemDataActionPerformed

    private void JTFtitulocargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtitulocargoActionPerformed
       String texto = JTFtitulocargo.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
            titulocargoSelecionado=true;
        }
         JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JTFtitulocargoActionPerformed

    private void JTFempregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFempregadorActionPerformed
        String texto = JTFempregador.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
            empregadorSelecionado=true;
        }
          JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JTFempregadorActionPerformed

    private void JTFcidadeProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcidadeProActionPerformed
         String texto = JTFcidadePro.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
            cidadeProSelecionado=true;
        }
            JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JTFcidadeProActionPerformed

    private void JTFestadoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFestadoProActionPerformed
        String texto = JTFestadoPro.getText();
         proximo =(texto != null && !texto.isEmpty());
          if(proximo){
            estadoProSelecionado=true;
        }
            JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JTFestadoProActionPerformed

    private void JCBanoinicioProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBanoinicioProActionPerformed
         if(JCBanoinicioPro.getSelectedItem() != null){
        anoInicioProSelecionado = true;
        }
           JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JCBanoinicioProActionPerformed

    private void JCBanoterminoPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBanoterminoPROActionPerformed
       if(JCBanoterminoPRO.getSelectedItem() != null){
        anoTerminoProSelecionado = true;
        }
            JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JCBanoterminoPROActionPerformed

    private void JRBtrabalhajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBtrabalhajaActionPerformed
        if(JRBtrabalhaja.isSelected()){
            trabalhajaSelecionado=true;
            anoTerminoProSelecionado=false;
           JCBanoterminoPRO.setEnabled(false);
       } 
       if(!JRBtrabalhaja.isSelected()){
           trabalhajaSelecionado=false;
            JBProximoProfi.setEnabled(false);
            JCBanoterminoPRO.setEnabled(true);
       }
         JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JRBtrabalhajaActionPerformed

    private void JRBsemExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBsemExpActionPerformed
         if(JRBsemExp.isSelected()){
             semExpSelecionado=true;
           JBProximoProfi.setEnabled(true);
           JTFtitulocargo.setEnabled(false);
           JTFempregador.setEnabled(false);
           JTFcidadePro.setEnabled(false);
           JTFestadoPro.setEnabled(false);
           JCBanoinicioPro.setEnabled(false);
           JCBanoterminoPRO.setEnabled(false);
           JRBtrabalhaja.setEnabled(false);
       } 
       if(!JRBsemExp.isSelected()){
           semExpSelecionado=false;
          JBProximoProfi.setEnabled(false);
          JTFtitulocargo.setEnabled(true);
           JTFempregador.setEnabled(true);
           JTFcidadePro.setEnabled(true);
           JTFestadoPro.setEnabled(true);
           JCBanoinicioPro.setEnabled(true);
           JCBanoterminoPRO.setEnabled(true);
           JRBtrabalhaja.setEnabled(true);
       }
         JBProximoProfiActionPerformed(evt);
    }//GEN-LAST:event_JRBsemExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Abas;
    private javax.swing.JButton JBProximoProfi;
    private javax.swing.JButton JBproximo;
    private javax.swing.JButton JBproximoFormacao;
    private javax.swing.JComboBox<String> JCBano;
    private javax.swing.JComboBox<String> JCBanoInicio;
    private javax.swing.JComboBox<String> JCBanoinicioPro;
    private javax.swing.JComboBox<String> JCBanotermino;
    private javax.swing.JComboBox<String> JCBanoterminoPRO;
    private javax.swing.JComboBox<String> JCBcnh;
    private javax.swing.JComboBox<String> JCBdia;
    private javax.swing.JComboBox<String> JCBestadocivil;
    private javax.swing.JComboBox<String> JCBmes;
    private javax.swing.JComboBox<String> JCBmesInicio;
    private javax.swing.JComboBox<String> JCBmesTermino;
    private javax.swing.JComboBox<String> JCBsituacao;
    private javax.swing.JRadioButton JRBsemData;
    private javax.swing.JRadioButton JRBsemExp;
    private javax.swing.JRadioButton JRBtrabalhaja;
    private javax.swing.JTextArea JTAresumo;
    private javax.swing.JTextField JTFcampoDeEstdo;
    private javax.swing.JTextField JTFcep;
    private javax.swing.JTextField JTFcidade;
    private javax.swing.JTextField JTFcidadePro;
    private javax.swing.JTextField JTFdiploma;
    private javax.swing.JTextField JTFemail;
    private javax.swing.JTextField JTFempregador;
    private javax.swing.JTextField JTFendereço;
    private javax.swing.JTextField JTFestado;
    private javax.swing.JTextField JTFestadoPro;
    private javax.swing.JTextField JTFinstituicao;
    private javax.swing.JTextField JTFlocalInst;
    private javax.swing.JTextField JTFnacionalidade;
    private javax.swing.JTextField JTFsobrenome;
    private javax.swing.JTextField JTFtelefone;
    private javax.swing.JTextField JTFtitulocargo;
    private javax.swing.JTextField JTnome;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
